ALTER TABLE users
    ALTER COLUMN first_name TYPE VARCHAR(512),
    ALTER COLUMN last_name TYPE VARCHAR(512),
    ALTER COLUMN phone_number TYPE VARCHAR(512),
    ALTER COLUMN identity_number TYPE VARCHAR(512),
    ALTER COLUMN address TYPE VARCHAR(512),
    ALTER COLUMN city TYPE VARCHAR(512),
    ALTER COLUMN country TYPE VARCHAR(512),
    ALTER COLUMN zip_code TYPE VARCHAR(512);

