spring:
  application:
    name: ecommerce-backend
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ecommerce}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2s
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

app:
  jwt:
    secret: ${JWT_SECRET:please-change-this-secret-key-to-32-char-minimum}
    issuer: ecommerce
    access-ttl: PT15M
    refresh-ttl: P7D
  security:
    refresh-cookie-name: ${REFRESH_COOKIE_NAME:refresh_token}
    refresh-cookie-path: ${REFRESH_COOKIE_PATH:/api/v1/auth}
    refresh-cookie-secure: ${REFRESH_COOKIE_SECURE:true}
    pii:
      encryption-key: ${PII_ENCRYPTION_KEY:MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=}
  payment:
    callback-url: ${PAYMENT_CALLBACK_URL:https://example-ngrok-domain.ngrok-free.app/api/v1/payments/callback}
    provider: ${PAYMENT_PROVIDER:iyzico}
    iyzico:
      api-key: ${IYZICO_API_KEY:}
      secret-key: ${IYZICO_SECRET_KEY:}
      base-url: ${IYZICO_BASE_URL:https://sandbox-api.iyzipay.com}
